# Common services

## PacketFence
packetfence:
  extends:
    file: ./services/packetfence/compose.yml
    service: packetfence
    # ports:
    # do not exposes ports because uses the native network stack. Configuration portal is on: https://ip:1443

casserver:
  extends:
    file: ./services/cas/compose.yml
    service: cas
  ports:
    - "8080:8080"
    - "8443:8443"

## CorpPortal
corpportal-web:
  extends:
    file: ./services/corpportal/compose.yml
    service: corpportal-web
  ports:
    - "80:9000"
    - "35729:35729"
  links:
    - corpportal-db:db
    - casserver
  environment:
    - APP_OWNCLOUD=true
    - APP_ZIMBRA=true
    - APP_REDMINE=true
    - APP_OPENFIRE=true
    - MASTER_FQDN=comcloud-domain

  volumes:
    - ./data/company-logo.png:/usr/src/app/client/assets/images/logo.png:ro

corpportal-db:
  extends:
    file: ./services/corpportal/compose.yml
    service: corpportal-db

# Specific services

## Owncloud
owncloud:
  build: services/owncloud
  links: 
    - casserver
  ports:
    - "8081:80"
  hostname: owncloud
  domainname: comcloud-domain

# Zimbra
zimbra:
  build: services/zimbra
  links: 
    - casserver
  ports:
    - "8082:443"
    - "7071:7071"
  environment:
    - PASSWORD=docker
  hostname: zimbra
  domainname: comcloud-domain

# Redmine
redmine:
  build: services/redmine
  links: 
    - casserver
  ports:
    - "8083:3000"
  hostname: redmine
  domainname: comcloud-domain

# Jabber
openfire:
  build: services/openfire
  links: 
    - casserver
  ports:
    - "9090:9090"
    - "9091:9091"
    - "5222:5222"
    - "5223:5223"
    - "8084:7070"
    - "7777:7777"
    - "7443:7443"
    - "5229:5229"
    - "5269:5269"
  hostname: openfire
  domainname: comcloud-domain
